---
- name: Google APT repo key added
  apt_key:
    url: "{{ google_chrome_gpgkey }}"
    state: present
  become: yes
  tags:
    - google-chrome
    - apt-repos
    - repos

- name: Google Chrome APT repo added
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
  become: yes
  tags:
    - google-chrome
    - apt-repos
    - repos
