---
- name: Include repo tasks
  include: "{{ ansible_os_family | lower }}.yml"
  tags:
    - google-chrome
    - repos

- name: Google Chrome installed
  package:
    name: google-chrome-stable
    state: present
  become: yes
  tags:
    - google-chrome
    - packages
