---
- name: Google Chrome YUM repo added
  yum_repository:
    name: google-chrome
    description: Google Chrome
    baseurl: "{{ google_chrome_rpm_repo }}"
    gpgkey: "{{ google_chrome_gpgkey }}"
    state: present
  become: yes
  tags:
    - google-chrome
    - rpm-repos
    - repos
